[PHP]
variables_order = "EGPCS"
max_execution_time = 300
memory_limit = 256M
error_reporting = E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED & ~E_NOTICE
display_errors = Off
log_errors = On
post_max_size = 100M
upload_max_filesize = 100M
date.timezone = America/Sao_Paulo
short_open_tag = On
